name: CI/CD Pipeline Automatizacion

on:
  pull_request:
    branches:
      - main 
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli@16.2.5

      - name: Run tests
        run: ng test --watch=false --browsers=ChromeHeadless

      - name: Build
        run: npm run build
